server:
  port: 9000
  servlet:
    context-path: /api/v1/product-service

spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://root:${mongodb-root-password}@${MONGODB_SERVICE_HOST}:${MONGODB_SERVICE_PORT}
      database: p2p

    storage:
      bucket-name: images-burner-p2p
  cloud:
    openfeign:
      client:
        config:
          image-service:
            url: ${SVC_IMG}
          index-service:
            url: ${SVC_INX}
          profile-service:
            url: ${SVC_PRF}
          notification-service:
            url: ${SVC_NOT}


springdoc:
  api-docs:
    enabled: true
    path: /rest-api-docs
  swagger-ui:
    path: /swagger-ui

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - health
          - metrics
          - info

  endpoint:
    metrics:
      enabled: true
  prometheus:
    enabled: true

images:
  number:
    restriction: 5

secret: mvpp2p
errorMsgMap:
  ERR_DETAIL_NOT_FOUND: "Details could not be found. {0}"
  ERR_SAVING_DATA: "Error in saving data. {0}"
  ERR_UPDATING_DATA: "Error in updating data. {0}"
  ERR_DELETING_DATA: "Error in deleting data. {0}"
  ERR_JSON_TRANFORMATION_FAILURE: "Tranformation Fails. {0}"
  ERR_RESPONSE_NOT_FOUND: "No Response Received. {0}"
  ERR_RESPONSE_BODY_NOT_FOUND: "Details not found. {0}"
  ERR_AUTHENTICATION: "Unauthorized Access : {0}"